name: Postman CLI CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run collection
        run: |
          postman collection run 4182217-69eb2a84-39e9-4337-97ba-017ccd73d212 -e 4182217-4e6c0642-15a1-403c-97ff-f1bf5801bb16

