name: Run Postman and Send Email

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman and HTML reporter
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Run Postman collection
        run: |
          newman run MyCollection.json \
            -e MyEnvironment.json \
            -r htmlextra \
            --reporter-htmlextra-export newman-report.html

      - name: Send email with report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Postman Test Report Test"
          to: thong.tq95@gmail.com
          from: "GitHub Actions <${{ secrets.EMAIL_USERNAME }}>"
          body: "Postman tests have completed. Please see the attached report."
          attachments: newman-report.html
